package models;


public enum EBar {

    LA_TABERNA,
    EL_REFUGIO,
    LA_CAVA,
    EL_RINCON_DEL_VINO,
    LA_CERVECERIA,
    BAR_MALTEADO,
    HOPS_AND_DREAMS,
    LA_FABRICA,
    LA_BARRICA,
    BREWHOUSE,
    LUPULO_VIVO,
    LA_PIOJERA,
    EL_MESON_DEL_DIABLO,
    BAR_LIGURIA,
    EL_HUASO_ALEGRE,
    THE_DRUNKEN_MONK,
    THE_BEER_GARDEN,
    THE_BLACK_CAT,
    THE_OLD_BREWERY,
    THE_GOLDEN_TAP,
    ENTRE_ESPUMAS,
    TRENTA_Y_TRES_SUR,
    LA_ESPUMOSA,
    LA_BARRA_INFINITA,
    MALTERIA_OCULTA
}
